#! /bin/bash

declare -A DOT_ALIASES
DOT_ALIASES[.]="dot"
DOT_ALIASES[..]="dot .."
DOT_ALIASES[...]="dot ..."
DOT_ALIASES[.,]="dot --hidden"
DOT_ALIASES[,.]="dot --hidden"
DOT_ALIASES[.x]="dot -x"
DOT_ALIASES[.h]="dot -h"
DOT_ALIASES[.s]="dot -s"
DOT_ALIASES[.a]="dot -a"
DOT_ALIASES[.p]="dot -p"
DOT_ALIASES[.d]="dot -d"
DOT_ALIASES[.n]="dot -n"
DOT_ALIASES[.rc]="dot -rc"
DOT_ALIASES[.rm]="dot -rm"
DOT_ALIASES[.mf]="dot -m -f"
DOT_ALIASES[.md]="dot -m -d"
DOT_ALIASES[.mv]="dot --move"
DOT_ALIASES[.t]="dot -t"

for alias in ${!DOT_ALIASES[@]}; do
    alias $alias="${DOT_ALIASES[$alias]}"
done

_._completion() {
    local current_word="${COMP_WORDS[COMP_CWORD]}"
    local aliases=${!DOT_ALIASES[@]}

    COMPREPLY=( $(compgen -W "${aliases}" -- "${current_word}") )
}

complete -F _._completion .

