#! /bin/bash

declare -A DOT_ALIASES
DOT_ALIASES[.]="dot nav"
DOT_ALIASES[..]="dot nav .."
DOT_ALIASES[...]="dot nav ..."
DOT_ALIASES[.rc]="dot nav rc"
DOT_ALIASES[.h]="dot nav h"
DOT_ALIASES[.lf]="dot lsf"
DOT_ALIASES[.ld]="dot lsd"
DOT_ALIASES[.la]="dot lsa"
DOT_ALIASES[.,]="dot lsa"
DOT_ALIASES[,.]="dot lsa"
DOT_ALIASES[.x]="dot x"
DOT_ALIASES[.s]="dot s"
DOT_ALIASES[.a]="dot a"
DOT_ALIASES[.p]="dot p"
DOT_ALIASES[.d]="dot d"
DOT_ALIASES[.b]="dot d --undo"
DOT_ALIASES[.n]="dot new"
DOT_ALIASES[.rm]="dot rm"
DOT_ALIASES[.mf]="dot mkf"
DOT_ALIASES[.md]="dot mkd"
DOT_ALIASES[.mv]="dot mv"

for alias in ${!DOT_ALIASES[@]}; do
    alias $alias="${DOT_ALIASES[$alias]}"
done

function _._completion() {
    local current_word="${COMP_WORDS[COMP_CWORD]}"
    local previous_word="${COMP_WORDS[COMP_CWORD-1]}"
    local aliases=${!DOT_ALIASES[@]}

    if [[ "$current_word" == "." && "$previous_word" == "" ]]; then
        COMPREPLY=( $(compgen -W "${aliases}" -- "${current_word}") )
    else
        local IFS=$'\n'
        compopt -o nospace
        if [[ "$current_word" == */* ]]; then
            local dir="${current_word%/*}/"
            local prefix="${current_word##*/}"
        else
            local dir=""
            local prefix="$current_word"
        fi
        COMPREPLY=( $(compgen -f -- "$dir$prefix" | grep -v '^\.') )
        for i in "${!COMPREPLY[@]}"; do
            if [[ -d "${COMPREPLY[i]}" ]]; then
                COMPREPLY[i]+='/'
            fi
        done 
    fi
}

function _.a_completion() {
    local CONFIG_FILE="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)/yml/dot.yml"
    local current_word="${COMP_WORDS[COMP_CWORD]}"
    local alias_path=".aliases"

    if [[ ! -f "$CONFIG_FILE" ]]; then
        echo "Configuration file not found at $CONFIG_FILE" >&2
        return
    fi

    for (( i = 1; i < COMP_CWORD; i++ )); do
        if [[ "${COMP_WORDS[i]}" != "--alias" && "${COMP_WORDS[i]}" != -* ]]; then
            alias_path+=".${COMP_WORDS[i]//\//}"
        fi
    done

    local subkeys=()
    local all_keys=$(yq eval "$alias_path | keys" "$CONFIG_FILE" 2>/dev/null | sed 's/- //g')

    for key in $all_keys; do
        if [[ "$key" != "path" && "$key" != "action" && "$key" != "recursive" && "$key" != "depth" ]]; then
            subkeys+=("$key")
        fi
    done

    local base_path
    local full_path
    local files=()

    if [[ "$current_word" == */ ]]; then
        alias_path+=".$(echo "$current_word" | tr -d '/')"
        base_path=$(yq eval "${alias_path}.path" "$CONFIG_FILE" 2>/dev/null)
        full_path=$base_path

        if [[ -d "$full_path" ]]; then
            files=($(ls -1p "$full_path" | grep '/$'))
           # echo "Files: ${files[*]}" # Debug statement.
            COMPREPLY=($(compgen -W "${files[*]}" -- "$current_word"))
        fi

    elif [[ "$current_word" == */* ]]; then
        base_path=$(yq eval "${alias_path}.path" "$CONFIG_FILE" 2>/dev/null)
        new_path="$base_path/${current_word%/*}"

        if [[ -d "$new_path" ]]; then
            files=($(ls -1p "$new_path"))
            #echo "Files: ${files[*]}" # Debug statement.
            COMPREPLY=($(compgen -W "${files[*]}" -- "${current_word##*/}"))
        fi
        
    else
        #echo "Subkeys: ${subkeys[*]}" # Debug statement.
        COMPREPLY=($(compgen -W "${subkeys[*]}" -- "$current_word"))
    fi
}

complete -F _._completion .
complete -F _.a_completion .a
