#! /bin/bash

function dot() {
    local CONFIG_FILE="${BASH_SOURCE%/*}/yml/dot.yml"
    source ${BASH_SOURCE%/*}/sh/nav.sh
    source ${BASH_SOURCE%/*}/sh/help.sh   
    source ${BASH_SOURCE%/*}/sh/exec.sh   
    source ${BASH_SOURCE%/*}/sh/del.sh
    source ${BASH_SOURCE%/*}/sh/rm.sh
    source ${BASH_SOURCE%/*}/sh/alias.sh
    source ${BASH_SOURCE%/*}/sh/preview.sh
    source ${BASH_SOURCE%/*}/sh/source.sh
    source ${BASH_SOURCE%/*}/sh/mv.sh
    source ${BASH_SOURCE%/*}/sh/make.sh

    declare -A DOT_ACTIONS
    DOT_ACTIONS=()
    DOT_ACTIONS[help]="dot_help --help"
    DOT_ACTIONS[nav]="dot_nav n nav"
    DOT_ACTIONS[exec]="dot_exec x exec"
    DOT_ACTIONS[source]="dot_src s src source"
    DOT_ACTIONS[list]="dot_ls l ls list"
    DOT_ACTIONS[list_file]="dot_lsf lsf list-file"
    DOT_ACTIONS[list_dir]="dot_lsd lsd list-dir"
    DOT_ACTIONS[list_all]="dot_lsa lsa list-all"
    DOT_ACTIONS[del]="dot_del d del delete"
    DOT_ACTIONS[preview]="dot_preview p prev preview"
    DOT_ACTIONS[remove]="dot_remove rm remove"
    DOT_ACTIONS[rename]="dot_rename rn rename"
    DOT_ACTIONS[make]="dot_make mk make"
    DOT_ACTIONS[make_file]="dot_mkf mkf make-dir"
    DOT_ACTIONS[make_dir]="dot_mkd mkd make-dir"

    declare -A DOT_FUNCTIONS
    DOT_FUNCTIONS=()
    for action in "${!DOT_ACTIONS[@]}"; do
        local entry="${DOT_ACTIONS[$action]}"
        local function_name="${entry%% *}"
        DOT_FUNCTIONS[$action]="$function_name"
    done

    declare -A DOT_OPTIONS
    DOT_OPTIONS=()
    for action in "${!DOT_ACTIONS[@]}"; do
        local entry="${DOT_ACTIONS[$action]}"
        local function_options="${entry#* }"
        DOT_OPTIONS[$action]="${function_options}"
    done
    
    if [[ -z "$1" ]]; then
        "${DOT_FUNCTIONS[help]}"
        return 0
    else
        match_action=1
        for action in ${!DOT_ACTIONS[@]}; do
            options=(${DOT_OPTIONS[$action]})
            for opt in ${options[@]}; do
                if [[ "$1" == "$opt" ]]; then
                    shift 1
                    "${DOT_FUNCTIONS[$action]}" "$@"
                    match_action=0
                    return 0
                fi
            done
        done
        if ! $match_action; then
            "${DOT_FUNCTIONS[help]}"
            return 1
        fi
    fi 
}
